name: build docker

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
    inputs:
      test:
        required: false
        default: '1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract Version
        id: version_step
        run: |
          echo "VERSION=${GITHUB_REF#$"refs/tags/v"}" >> $GITHUB_ENV
          echo "VERSION_TAG=$GITHUB_REPOSITORY:${GITHUB_REF#$"refs/tags/v"}" >> $GITHUB_ENV
          echo "LATEST_TAG=$GITHUB_REPOSITORY:latest" >> $GITHUB_ENV


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: BuildDockerImage
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ env.VERSION_TAG }}
            ${{ env.LATEST_TAG }}
          file: ./Dockerfile
    